### ISSUE TITLE
Issue with web-based tool

### ISSUE THREAD

**Issue by rtk29** [realChrisHahn2/nl2spec#3]
Hi,

1. Is following the READ_ME file enough to reproduce the results with the given dataset in the experiments folder ?
2. The web-based tool with the address http://127.0.0.1:5000/ is not accessible.

![image](https://github.com/realChrisHahn2/nl2spec/assets/127055206/e60b7d6f-5798-455b-bf78-33eaaf4e174b)

**Comment by dmmendo** [comment]
1. The trend of the results in the [paper](https://arxiv.org/abs/2303.04864) are reproducible, however, the results may vary since the output of the ML models is not deterministic. Also, Codex has been discontinued and thus results with Codex are no longer reproducible.
2. try `python3 -m flask --app frontend.py run --host 0.0.0.0` and use the web address printed to the terminal.
